### ISSUE TITLE
Incorrect ontology assignment

### ISSUE THREAD

**Issue by chadlaing** [superphy/version-1#10]
In the VF ontology, we have the different allelic variations of the gene "eae", which encodes intimin.
All of these are listed in the "Non-LEE encoded TTSS effectors" category under "cytotoxic necrotizing factor". This is a major classifying error.

**Comment by amanji** [comment]
They are primarily categorized under Adherence as well. I think the effector classification was secondary, but we can have that classification removed from the ontology.

**Comment by chadlaing** [comment]
Yes, under Adherence is correct. We should remove the "non-LEE, cytotoxic necrotizing factor" assignment.

**Comment by chadlaing** [comment]
Fixed!
