### ISSUE TITLE
Allele histogram in VF-AMR - double check counts 

### ISSUE THREAD

**Issue by chadlaing** [superphy/version-1#3]
It appears that the allele frequency may be over-counter -- need to double check

**Comment by mwhitesi** [comment]
The allele histogram show the number of genomes with 0, 1, 2, ... , >=5 copies of a gene. So the bars should add up to 1641 (the number of genomes) when looking at a single gene.

**Comment by chadlaing** [comment]
Doubled checked, and the counts are correct.
